# Generated by Django 5.1.4 on 2024-12-17 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_holder', models.CharField(choices=[('HK', 'Hannah'), ('CC', 'Carlos'), ('J', 'Joint Account')], max_length=2)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_type', models.CharField(choices=[('A', 'Asset'), ('C', 'Cash'), ('D', 'Debt'), ('S', 'Savings')], max_length=2)),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 12, 17, 1, 50, 29, 957105))),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('latest_transaction_id', models.BigIntegerField()),
            ],
        ),
    ]
