# Generated by Django 5.1.4 on 2024-12-17 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_mortgage_alter_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 2, 51, 50, 961556)),
        ),
    ]
